// Generated by CoffeeScript 1.9.3
Ext.define('Purple.view.EditPaymentMethodForm', {
  extend: 'Ext.form.Panel',
  xtype: 'editpaymentmethodform',
  requires: ['Ext.form.*', 'Ext.field.*', 'Ext.Button'],
  config: {
    layout: {
      type: 'hbox',
      pack: 'start',
      align: 'start'
    },
    height: '100%',
    submitOnAction: false,
    cls: ['request-form', 'vehicle-form', 'accent-bg', 'slideable'],
    scrollable: {
      disabled: Ext.os.name === "Android",
      direction: 'vertical',
      directionLock: true,
      translatable: {
        translationMethod: 'auto'
      }
    },
    listeners: {
      initialize: function() {
        if (this.config.paymentMethodId !== 'new') {
          return this.getAt(1).add([
            {
              xtype: 'spacer',
              flex: 0,
              height: 100
            }, {
              xtype: 'container',
              flex: 0,
              layout: {
                type: 'vbox',
                pack: 'start',
                align: 'center'
              },
              cls: 'links-container',
              style: "width: 100%;\ntext-align: center;\npadding-bottom: 20px;",
              items: [
                {
                  xtype: 'button',
                  ui: 'plain',
                  text: 'Delete Card',
                  handler: (function(_this) {
                    return function() {
                      return _this.fireEvent('deletePaymentMethod', _this.config.paymentMethodId);
                    };
                  })(this)
                }
              ]
            }
          ]);
        }
      }
    },
    items: [
      {
        xtype: 'spacer',
        flex: 1
      }, {
        xtype: 'container',
        flex: 0,
        width: '85%',
        layout: {
          type: 'vbox',
          pack: 'start',
          align: 'start'
        },
        items: [
          {
            xtype: 'component',
            flex: 0,
            ctype: 'editPaymentMethodFormHeading',
            cls: 'heading',
            html: ''
          }, {
            xtype: 'component',
            flex: 0,
            cls: 'horizontal-rule'
          }, {
            xtype: 'textfield',
            ctype: 'editPaymentMethodFormCardNumber',
            name: 'card_number',
            label: 'Card Number',
            labelWidth: 125,
            flex: 0,
            cls: ['bottom-margin', 'uppercase-input'],
            clearIcon: false,
            component: {
              type: 'tel'
            }
          }, {
            xtype: 'selectfield',
            flex: 0,
            name: 'card_exp_month',
            label: 'Exp. Month',
            labelWidth: 110,
            listPicker: {
              title: 'Expiration Month'
            },
            cls: ['click-to-edit', 'bottom-margin'],
            options: [
              {
                text: '1 (January)',
                value: '1'
              }, {
                text: '2 (February)',
                value: '2'
              }, {
                text: '3 (March)',
                value: '3'
              }, {
                text: '4 (April)',
                value: '4'
              }, {
                text: '5 (May)',
                value: '5'
              }, {
                text: '6 (June)',
                value: '6'
              }, {
                text: '7 (July)',
                value: '7'
              }, {
                text: '8 (August)',
                value: '8'
              }, {
                text: '9 (September)',
                value: '9'
              }, {
                text: '10 (October)',
                value: '10'
              }, {
                text: '11 (November)',
                value: '11'
              }, {
                text: '12 (December)',
                value: '12'
              }
            ]
          }, {
            xtype: 'selectfield',
            flex: 0,
            name: 'card_exp_year',
            label: 'Exp. Year',
            labelWidth: 110,
            listPicker: {
              title: 'Expiration Year'
            },
            cls: ['click-to-edit', 'bottom-margin'],
            value: '2015',
            options: [
              {
                text: '2015',
                value: '2015'
              }, {
                text: '2016',
                value: '2016'
              }, {
                text: '2017',
                value: '2017'
              }, {
                text: '2018',
                value: '2018'
              }, {
                text: '2019',
                value: '2019'
              }, {
                text: '2020',
                value: '2020'
              }, {
                text: '2021',
                value: '2021'
              }, {
                text: '2022',
                value: '2022'
              }, {
                text: '2023',
                value: '2023'
              }, {
                text: '2024',
                value: '2024'
              }, {
                text: '2025',
                value: '2025'
              }, {
                text: '2026',
                value: '2026'
              }, {
                text: '2027',
                value: '2027'
              }, {
                text: '2028',
                value: '2028'
              }, {
                text: '2029',
                value: '2029'
              }, {
                text: '2030',
                value: '2030'
              }, {
                text: '2031',
                value: '2031'
              }, {
                text: '2032',
                value: '2032'
              }, {
                text: '2033',
                value: '2033'
              }
            ]
          }, {
            xtype: 'textfield',
            ctype: 'editPaymentMethodFormCVC',
            name: 'card_cvc',
            label: 'CVC',
            labelWidth: 125,
            flex: 0,
            cls: ['bottom-margin', 'uppercase-input'],
            clearIcon: false,
            component: {
              type: 'tel'
            }
          }, {
            xtype: 'container',
            flex: 0,
            height: 110,
            width: '100%',
            padding: '0 0 5 0',
            layout: {
              type: 'vbox',
              pack: 'center',
              align: 'center'
            },
            items: [
              {
                xtype: 'button',
                ui: 'action',
                cls: 'button-pop',
                text: 'Save Changes',
                flex: 0,
                handler: function() {
                  return this.up().up().up().fireEvent('saveChanges', this.up().up().up().config.saveChangesCallback);
                }
              }
            ]
          }
        ]
      }, {
        xtype: 'spacer',
        flex: 1
      }
    ]
  }
});
