// Generated by CoffeeScript 1.3.3

Ext.define('Purple.view.LoginForm', {
  extend: 'Ext.form.Panel',
  xtype: 'loginform',
  requires: ['Ext.form.*', 'Ext.field.*', 'Ext.Button'],
  config: {
    layout: {
      type: 'hbox',
      pack: 'center',
      align: 'center'
    },
    cls: ['login-form', 'strong-accent-bg'],
    scrollable: false,
    submitOnAction: false,
    items: [
      {
        xtype: 'container',
        id: 'registerButtonContainer',
        flex: 0,
        layout: {
          type: 'vbox',
          pack: 'start',
          align: 'center'
        },
        cls: 'links-container',
        style: "position: absolute;\nbottom: 15px;\nwidth: 100%;\ntext-align: center;",
        items: [
          {
            xtype: 'button',
            ui: 'plain',
            text: 'Register',
            handler: function() {
              return this.up().up().fireEvent('registerButtonTap');
            }
          }
        ]
      }, {
        xtype: 'spacer',
        flex: 1
      }, {
        xtype: 'container',
        flex: 0,
        width: '75%',
        layout: {
          type: 'vbox',
          pack: 'center',
          align: 'center'
        },
        items: [
          {
            xtype: 'spacer',
            flex: 1
          }, {
            xtype: 'component',
            flex: 0,
            padding: '0 0 30px 0',
            html: "<img src=\"resources/images/logo-light.png\" class=\"login-logo\" />"
          }, {
            xtype: 'emailfield',
            id: 'emailAddressField',
            flex: 0,
            name: 'email_address',
            clearIcon: false,
            value: ''
          }, {
            xtype: 'component',
            cls: 'special-label',
            flex: 0,
            html: 'email'
          }, {
            xtype: 'passwordfield',
            id: 'passwordField',
            flex: 0,
            name: 'password',
            clearIcon: false,
            value: ''
          }, {
            xtype: 'component',
            cls: 'special-label',
            flex: 0,
            html: 'password'
          }, {
            xtype: 'container',
            id: 'loginButtonContainer',
            flex: 0,
            height: 110,
            padding: '27 0 10 0',
            layout: {
              type: 'vbox',
              pack: 'center',
              align: 'center'
            },
            items: [
              {
                xtype: 'button',
                ui: 'action',
                cls: 'button-pop',
                text: 'Login',
                flex: 0,
                handler: function() {
                  return this.up().up().up().fireEvent('nativeLogin');
                }
              }
            ]
          }, {
            xtype: 'component',
            flex: 0,
            html: 'or login with',
            style: 'color: #ffffff;'
          }, {
            xtype: 'container',
            flex: 0,
            padding: '8 0 10 0',
            layout: {
              type: 'hbox',
              pack: 'center',
              align: 'center'
            },
            items: [
              {
                xtype: 'spacer',
                flex: 1
              }, {
                xtype: 'button',
                cls: 'icon-login-button',
                ui: 'plain',
                html: "<img src=\"resources/images/facebook-logo.png\" />",
                flex: 0,
                handler: function() {
                  return this.up().up().up().fireEvent('facebookLogin');
                }
              }, {
                xtype: 'spacer',
                flex: 1
              }, {
                xtype: 'button',
                cls: 'icon-login-button',
                ui: 'plain',
                html: "<img src=\"resources/images/google-logo.png\" />",
                flex: 0,
                handler: function() {
                  return this.up().up().up().fireEvent('facebookLogin');
                }
              }, {
                xtype: 'spacer',
                flex: 1
              }
            ]
          }, {
            xtype: 'spacer',
            flex: 1
          }
        ]
      }, {
        xtype: 'spacer',
        flex: 1
      }
    ]
  }
});
