// Generated by CoffeeScript 1.3.3

Ext.define('Purple.view.MainContainer', {
  extend: 'Ext.Container',
  xtype: 'maincontainer',
  config: {
    cls: 'accent-bg',
    layout: {
      type: 'card'
    }
  },
  initialize: function() {
    return this.callParent(arguments);
  }
});
