// Generated by CoffeeScript 1.3.3

Ext.define('Purple.view.RequestForm', {
  extend: 'Ext.form.Panel',
  xtype: 'requestform',
  requires: ['Ext.form.*', 'Ext.field.*', 'Ext.Button'],
  config: {
    layout: 'vbox',
    submitOnAction: true,
    items: [
      {
        xtype: 'textfield',
        name: 'time'
      }
    ]
  }
});
