// Generated by CoffeeScript 1.3.3

Ext.define('Purple.view.Vehicles', {
  extend: 'Ext.form.Panel',
  xtype: 'vehicles',
  requires: ['Ext.form.*', 'Ext.field.*', 'Ext.Button'],
  config: {
    layout: {
      type: 'hbox',
      pack: 'start',
      align: 'start'
    },
    submitOnAction: false,
    cls: ['accent-bg'],
    items: [
      {
        xtype: 'spacer',
        flex: 1
      }, {
        xtype: 'container',
        flex: 0,
        width: '85%',
        layout: {
          type: 'vbox',
          pack: 'start',
          align: 'start'
        },
        items: [
          {
            xtype: 'component',
            flex: 0,
            cls: 'heading',
            html: 'Vehicles'
          }, {
            xtype: 'component',
            flex: 0,
            cls: 'horizontal-rule'
          }
        ]
      }, {
        xtype: 'spacer',
        flex: 1
      }
    ]
  }
});
