// Generated by CoffeeScript 1.3.3
var VERSION;

VERSION = "LOCAL";

window.util = {
  WEB_SERVICE_BASE_URL: (function() {
    switch (VERSION) {
      case "LOCAL":
        return "http://192.168.1.124:3000/";
      case "PROD":
        return "https://service.purpleapp.com/";
      case "DEV":
        return "http://purple-dev.elasticbeanstalk.com/";
    }
  })(),
  ctl: function(controllerName) {
    return Purple.app.getController(controllerName);
  },
  strToTitleCase: function(str) {
    return str.replace(/\w\S*/g, function(word) {
      return word.charAt(0).toUpperCase() + word.substr(1).toLowerCase();
    });
  }
};
