// Generated by CoffeeScript 1.9.3
Ext.define('Override.form.Panel', {
  override: 'Ext.form.Panel',
  getElementConfig: function() {
    var config;
    config = this.callParent();
    config.tag = "div";
    config.children.push({
      tag: 'input',
      type: 'submit',
      style: 'visibility: hidden; width: 0; height: 0; position: absolute; right: 0; bottom: 0;'
    });
    return config;
  },
  submit: function(options, e) {
    return false;
    options = options || {};
    return this.callParent([options, e]);
  }
});
