// Generated by CoffeeScript 1.10.0
Ext.define('Ux.field.CreditCardField', {
  extend: 'Ext.field.Text',
  xtype: 'creditcardfield',
  onKeyup: function(value) {
    var i, nStr, nums, r;
    nums = value.substr(0, 19).replace(/[^\d]/gi, '');
    r = nums.match(/(\d){4}/g);
    if (r) {
      i = 0;
      nStr = '';
      while (i < r.length) {
        nStr += i !== r.length - 1 ? r[i] + (i < 3 ? '-' : '') : r[i];
        i++;
      }
      return this.setValue(nums.length % 4 !== 0 ? nStr + '-' + nums.substr(r.length * 4, nums.length) : nStr);
    } else {
      return this.setValue(nums);
    }
  }
});
