// Generated by CoffeeScript 1.9.3
Ext.define('Ux.field.MoneyField', {
  extend: 'Ext.field.Text',
  xtype: 'moneyfield',
  applyValue: function(value) {
    return Ext.util.Format.format('${0}', value);
  }
});
