// Generated by CoffeeScript 1.9.3
Ext.define('Ux.field.PhoneField', {
  extend: 'Ext.field.Text',
  xtype: 'phonefield',
  applyValue: function(value) {
    return Ext.util.Format.format('{0}', value);
  }
});
