// Generated by CoffeeScript 1.10.0
Ext.define('Ux.field.SelectOtherField', {
  extend: 'Ext.field.Select',
  xtype: 'selectotherfield',
  config: {
    otherText: 'Other...',
    promptTitle: 'New Option',
    promptMessage: 'Enter new option:'
  },
  addOtherField: function() {
    var opts;
    opts = this.getOptions();
    opts.push({
      text: this.getOtherText(),
      value: this.getOtherText()
    });
    return this.updateOptions(opts);
  },
  fieldChange: function(cmp, newValue) {
    if (newValue === this.getOtherText()) {
      return Ext.Msg.prompt(this.getPromptTitle(), this.getPromptMessage(), (function(_this) {
        return function(choice, text) {
          if (choice === 'ok' && text.trim() !== '') {
            return _this.insertOption(text);
          }
        };
      })(this));
    }
  },
  insertOption: function(text) {
    return util.ctl("Vehicles").updateVehicleList(this._name, text);
  }
});
