// Generated by CoffeeScript 1.3.3

Ext.define('Purple.controller.Menu', {
  extend: 'Ext.app.Controller',
  config: {
    refs: {
      mainContainer: 'maincontainer',
      topToolbar: 'toptoolbar',
      feedbackButton: '[ctype=feedbackButton]',
      inviteButton: '[ctype=inviteButton]',
      requestGasTabContainer: '#requestGasTabContainer',
      accountTab: '#accountTab',
      accountTabContainer: '#accountTabContainer',
      loginForm: 'loginform',
      mapForm: 'mapform',
      map: '#gmap'
    },
    control: {
      feedbackButton: {
        feedbackButtonTap: 'feedbackButtonTap'
      },
      inviteButton: {
        inviteButtonTap: 'inviteButtonTap'
      },
      topToolbar: {
        helpButtonTap: 'helpButtonTap'
      }
    }
  },
  launch: function() {
    return this.callParent(arguments);
  },
  open: function() {
    return this.getMainContainer().openContainer();
  },
  close: function() {
    return this.getMainContainer().closeContainer();
  },
  isClosed: function() {
    return this.getMainContainer().isClosed();
  },
  helpButtonTap: function() {
    var _ref;
    if (this.getCurrentIndex() === 5) {
      return this.selectOption((_ref = this.indexBeforeHelp) != null ? _ref : 2);
    } else {
      this.indexBeforeHelp = this.getCurrentIndex();
      return this.selectOption(5);
    }
  },
  feedbackButtonTap: function() {
    return this.selectOption(6);
  },
  inviteButtonTap: function() {
    return this.selectOption(7);
  },
  getCurrentIndex: function() {
    return this.getMainContainer().getActiveItem().data.index;
  },
  selectOption: function(index) {
    return this.getMainContainer().getItems().getAt(0).select(index, false, false);
  },
  changeTitle: function(index, title) {
    return this.getMainContainer().getAt(0).getAt(2).getAt(index).setData({
      title: title
    });
  },
  showTitles: function(indicies) {
    var i, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = indicies.length; _i < _len; _i++) {
      i = indicies[_i];
      _results.push(this.getMainContainer().getAt(0).getAt(2).getAt(i).show());
    }
    return _results;
  },
  hideTitles: function(indicies) {
    var i, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = indicies.length; _i < _len; _i++) {
      i = indicies[_i];
      _results.push(this.getMainContainer().getAt(0).getAt(2).getAt(i).hide());
    }
    return _results;
  },
  adjustForAppLoginState: function() {
    var _ref, _ref1;
    if (util.ctl('Account').isUserLoggedIn()) {
      this.hideTitles([1]);
      if (util.ctl('Account').isCourier()) {
        this.hideTitles([0, 4]);
        this.showTitles([2, 3, 8, 9]);
        if ((_ref = localStorage['purpleCourierGallons87']) == null) {
          localStorage['purpleCourierGallons87'] = 0;
        }
        if ((_ref1 = localStorage['purpleCourierGallons91']) == null) {
          localStorage['purpleCourierGallons91'] = 0;
        }
        if (!(util.ctl('Main').courierPingIntervalRef != null)) {
          util.ctl('Main').initCourierPing();
        }
      } else {
        this.hideTitles([8, 9]);
        this.showTitles([2, 3, 4]);
      }
      return util.ctl('Account').populateAccountForm();
    } else {
      this.hideTitles([2, 3, 4, 8, 9]);
      return this.showTitles([1]);
    }
  }
});
