// Generated by CoffeeScript 1.3.3

Ext.define('Purple.controller.Menu', {
  extend: 'Ext.app.Controller',
  config: {
    refs: {
      mainContainer: 'maincontainer',
      topToolbar: 'toptoolbar',
      feedbackButton: '[ctype=feedbackButton]',
      inviteButton: '[ctype=inviteButton]',
      requestGasTabContainer: '#requestGasTabContainer',
      accountTab: '#accountTab',
      accountTabContainer: '#accountTabContainer',
      loginForm: 'loginform',
      mapForm: 'mapform',
      map: '#gmap'
    },
    control: {
      feedbackButton: {
        feedbackButtonTap: 'feedbackButtonTap'
      },
      inviteButton: {
        inviteButtonTap: 'inviteButtonTap'
      },
      topToolbar: {
        menuButtonTap: 'menuButtonTap',
        helpButtonTap: 'helpButtonTap'
      }
    }
  },
  launch: function() {
    return this.callParent(arguments);
  },
  menuButtonTap: function() {
    return this.getMainContainer().toggleContainer();
  },
  helpButtonTap: function() {
    return this.selectOption(5);
  },
  feedbackButtonTap: function() {
    return this.selectOption(6);
  },
  inviteButtonTap: function() {
    return this.selectOption(7);
  },
  selectOption: function(index) {
    return this.getMainContainer().getItems().getAt(0).select(index, false, false);
  },
  changeTitle: function(index, title) {
    return this.getMainContainer().getAt(0).getAt(2).getAt(index).setData({
      title: title
    });
  },
  showTitles: function(indicies) {
    var i, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = indicies.length; _i < _len; _i++) {
      i = indicies[_i];
      _results.push(this.getMainContainer().getAt(0).getAt(2).getAt(i).show());
    }
    return _results;
  },
  hideTitles: function(indicies) {
    var i, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = indicies.length; _i < _len; _i++) {
      i = indicies[_i];
      _results.push(this.getMainContainer().getAt(0).getAt(2).getAt(i).hide());
    }
    return _results;
  },
  adjustForAppLoginState: function() {
    if (util.ctl('Account').isUserLoggedIn()) {
      this.hideTitles([1]);
      this.showTitles([2, 3, 4]);
      return util.ctl('Account').populateAccountForm();
    } else {
      this.hideTitles([2, 3, 4]);
      return this.showTitles([1]);
    }
  }
});
