// Generated by CoffeeScript 1.3.3

Ext.define('Purple.controller.TopToolbar', {
  extend: 'Ext.app.Controller',
  requires: ['Purple.view.MainContainer', 'Purple.view.TopToolbar'],
  config: {
    refs: {
      mainContainer: 'maincontainer',
      topToolbar: 'toptoolbar',
      backButton: '[ctype=backButton]',
      infoButton: '[ctype=infoButton]'
    },
    control: {
      backButton: {
        backButtonTap: 'backButtonTap'
      },
      infoButton: {
        infoButtonTap: 'infoButtonTap'
      }
    }
  },
  backButtonTap: function() {
    return this.getBackButton().config.performAction();
  },
  helpButtonTap: function() {
    var text, _ref;
    text = (_ref = this.getMainContainer().getActiveItem().config.helpText) != null ? _ref : "No help info here.";
    return Ext.Msg.alert('Help?', text, (function() {}));
  }
});
