// Generated by CoffeeScript 1.3.3
var result, v, _i, _len;

result = {};

for (_i = 0, _len = json.length; _i < _len; _i++) {
  v = json[_i];
  if (!(result[v["Year"]] != null)) {
    result[v["Year"]] = {};
  }
  if (!(result[v["Year"]][v["Make"]] != null)) {
    result[v["Year"]][v["Make"]] = [];
  }
  if (result[v["Year"]][v["Make"]].indexOf(v["Model"]) === -1) {
    result[v["Year"]][v["Make"]].push(v["Model"]);
  }
}

document.write(JSON.stringify(result));
